--
-- PostgreSQL database dump
--

-- Dumped from database version 15.12 (Debian 15.12-1.pgdg120+1)
-- Dumped by pg_dump version 15.12 (Debian 15.12-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO helix;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO helix;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: async_task_statuses; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.async_task_statuses (
    task_id character varying(255) NOT NULL,
    task_name character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    progress integer NOT NULL,
    message text,
    result_data jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    repository_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT async_task_statuses_progress_check CHECK ((progress >= 0))
);


ALTER TABLE public.async_task_statuses OWNER TO helix;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO helix;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO helix;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO helix;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: code_classes; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.code_classes (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    start_line integer NOT NULL,
    end_line integer NOT NULL,
    structure_hash character varying(64),
    code_file_id bigint NOT NULL
);


ALTER TABLE public.code_classes OWNER TO helix;

--
-- Name: code_classes_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.code_classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.code_classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: code_dependencies; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.code_dependencies (
    id bigint NOT NULL,
    callee_id bigint NOT NULL,
    caller_id bigint NOT NULL
);


ALTER TABLE public.code_dependencies OWNER TO helix;

--
-- Name: code_dependencies_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.code_dependencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.code_dependencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: code_files; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.code_files (
    id bigint NOT NULL,
    file_path character varying(1024) NOT NULL,
    structure_hash character varying(64),
    repository_id bigint NOT NULL
);


ALTER TABLE public.code_files OWNER TO helix;

--
-- Name: code_files_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.code_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.code_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: code_symbols; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.code_symbols (
    id bigint NOT NULL,
    unique_id character varying(1024),
    name character varying(255) NOT NULL,
    start_line integer NOT NULL,
    end_line integer NOT NULL,
    content_hash character varying(64),
    documentation_hash character varying(64),
    documentation text,
    code_class_id bigint,
    code_file_id bigint,
    embedding public.vector(1536),
    documentation_status character varying(20) NOT NULL,
    is_orphan boolean NOT NULL,
    cyclomatic_complexity integer,
    loc integer,
    CONSTRAINT code_symbols_cyclomatic_complexity_check CHECK ((cyclomatic_complexity >= 0)),
    CONSTRAINT code_symbols_loc_check CHECK ((loc >= 0))
);


ALTER TABLE public.code_symbols OWNER TO helix;

--
-- Name: code_symbols_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.code_symbols ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.code_symbols_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO helix;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO helix;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO helix;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO helix;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO helix;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO helix;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO helix;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO helix;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO helix;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO helix;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO helix;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: embedding_batch_jobs; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.embedding_batch_jobs (
    id bigint NOT NULL,
    batch_id character varying(100) NOT NULL,
    input_file_id character varying(100) NOT NULL,
    output_file_id character varying(100),
    error_file_id character varying(100),
    status character varying(30) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    submitted_to_openai_at timestamp with time zone,
    openai_completed_at timestamp with time zone,
    results_processed_at timestamp with time zone,
    openai_metadata jsonb,
    custom_metadata jsonb,
    error_details text,
    repository_id bigint,
    job_type character varying(30) NOT NULL,
    completed_at timestamp with time zone
);


ALTER TABLE public.embedding_batch_jobs OWNER TO helix;

--
-- Name: embedding_batch_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.embedding_batch_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.embedding_batch_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knowledge_chunks; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.knowledge_chunks (
    id bigint NOT NULL,
    chunk_type character varying(20) NOT NULL,
    content text NOT NULL,
    embedding public.vector(1536),
    related_class_id bigint,
    related_file_id bigint,
    related_symbol_id bigint,
    repository_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.knowledge_chunks OWNER TO helix;

--
-- Name: knowledge_chunks_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.knowledge_chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.knowledge_chunks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: repositories; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.repositories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    full_name character varying(512) NOT NULL,
    github_id integer NOT NULL,
    status character varying(10) NOT NULL,
    root_merkle_hash character varying(64),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    last_processed timestamp with time zone,
    default_branch character varying(100) NOT NULL
);


ALTER TABLE public.repositories OWNER TO helix;

--
-- Name: repositories_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.repositories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repositories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: repository_insights; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.repository_insights (
    id bigint NOT NULL,
    commit_hash character varying(40) NOT NULL,
    insight_type character varying(30) NOT NULL,
    message text NOT NULL,
    data jsonb,
    is_resolved boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    related_symbol_id bigint,
    repository_id bigint NOT NULL
);


ALTER TABLE public.repository_insights OWNER TO helix;

--
-- Name: repository_insights_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.repository_insights ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repository_insights_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(200) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data jsonb NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.socialaccount_socialaccount OWNER TO helix;

--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.socialaccount_socialaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialapp; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL,
    provider_id character varying(200) NOT NULL,
    settings jsonb NOT NULL
);


ALTER TABLE public.socialaccount_socialapp OWNER TO helix;

--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.socialaccount_socialapp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialapp_sites; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.socialaccount_socialapp_sites (
    id bigint NOT NULL,
    socialapp_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialapp_sites OWNER TO helix;

--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.socialaccount_socialapp_sites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_sites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer
);


ALTER TABLE public.socialaccount_socialtoken OWNER TO helix;

--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.socialaccount_socialtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_notifications; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.user_notifications (
    id bigint NOT NULL,
    notification_type character varying(30) NOT NULL,
    message text NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    link_url character varying(512),
    repository_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_notifications OWNER TO helix;

--
-- Name: user_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.user_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    github_id integer
);


ALTER TABLE public.users OWNER TO helix;

--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO helix;

--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: helix
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO helix;

--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: helix
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: async_task_statuses async_task_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.async_task_statuses
    ADD CONSTRAINT async_task_statuses_pkey PRIMARY KEY (task_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: code_classes code_classes_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_classes
    ADD CONSTRAINT code_classes_pkey PRIMARY KEY (id);


--
-- Name: code_dependencies code_dependencies_caller_id_callee_id_f78c6c50_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_dependencies
    ADD CONSTRAINT code_dependencies_caller_id_callee_id_f78c6c50_uniq UNIQUE (caller_id, callee_id);


--
-- Name: code_dependencies code_dependencies_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_dependencies
    ADD CONSTRAINT code_dependencies_pkey PRIMARY KEY (id);


--
-- Name: code_files code_files_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_files
    ADD CONSTRAINT code_files_pkey PRIMARY KEY (id);


--
-- Name: code_files code_files_repository_id_file_path_8e0fcb37_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_files
    ADD CONSTRAINT code_files_repository_id_file_path_8e0fcb37_uniq UNIQUE (repository_id, file_path);


--
-- Name: code_symbols code_symbols_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_symbols
    ADD CONSTRAINT code_symbols_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: embedding_batch_jobs embedding_batch_jobs_batch_id_key; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.embedding_batch_jobs
    ADD CONSTRAINT embedding_batch_jobs_batch_id_key UNIQUE (batch_id);


--
-- Name: embedding_batch_jobs embedding_batch_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.embedding_batch_jobs
    ADD CONSTRAINT embedding_batch_jobs_pkey PRIMARY KEY (id);


--
-- Name: knowledge_chunks knowledge_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT knowledge_chunks_pkey PRIMARY KEY (id);


--
-- Name: repositories repositories_full_name_key; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.repositories
    ADD CONSTRAINT repositories_full_name_key UNIQUE (full_name);


--
-- Name: repositories repositories_github_id_key; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.repositories
    ADD CONSTRAINT repositories_github_id_key UNIQUE (github_id);


--
-- Name: repositories repositories_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.repositories
    ADD CONSTRAINT repositories_pkey PRIMARY KEY (id);


--
-- Name: repository_insights repository_insights_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.repository_insights
    ADD CONSTRAINT repository_insights_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq UNIQUE (socialapp_id, site_id);


--
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialapp
    ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp_sites_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);


--
-- Name: user_notifications user_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT user_notifications_pkey PRIMARY KEY (id);


--
-- Name: users users_github_id_key; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_github_id_key UNIQUE (github_id);


--
-- Name: users_groups users_groups_customuser_id_group_id_927de924_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_customuser_id_group_id_927de924_uniq UNIQUE (customuser_id, group_id);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_customuser_id_permission_2b4e4e39_uniq; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_customuser_id_permission_2b4e4e39_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX account_emailaddress_email_03be32b2 ON public.account_emailaddress USING btree (email);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: async_task_statuses_repository_id_f116b5f6; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX async_task_statuses_repository_id_f116b5f6 ON public.async_task_statuses USING btree (repository_id);


--
-- Name: async_task_statuses_task_id_43d2e877_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX async_task_statuses_task_id_43d2e877_like ON public.async_task_statuses USING btree (task_id varchar_pattern_ops);


--
-- Name: async_task_statuses_user_id_aad9e929; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX async_task_statuses_user_id_aad9e929 ON public.async_task_statuses USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: code_classes_code_file_id_e9e939cc; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX code_classes_code_file_id_e9e939cc ON public.code_classes USING btree (code_file_id);


--
-- Name: code_dependencies_callee_id_b1ace185; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX code_dependencies_callee_id_b1ace185 ON public.code_dependencies USING btree (callee_id);


--
-- Name: code_dependencies_caller_id_34f358d9; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX code_dependencies_caller_id_34f358d9 ON public.code_dependencies USING btree (caller_id);


--
-- Name: code_files_repository_id_d41da00e; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX code_files_repository_id_d41da00e ON public.code_files USING btree (repository_id);


--
-- Name: code_symbols_code_class_id_fd669541; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX code_symbols_code_class_id_fd669541 ON public.code_symbols USING btree (code_class_id);


--
-- Name: code_symbols_code_file_id_b3ae3485; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX code_symbols_code_file_id_b3ae3485 ON public.code_symbols USING btree (code_file_id);


--
-- Name: code_symbols_is_orphan_43d46ccf; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX code_symbols_is_orphan_43d46ccf ON public.code_symbols USING btree (is_orphan);


--
-- Name: code_symbols_unique_id_6564592d; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX code_symbols_unique_id_6564592d ON public.code_symbols USING btree (unique_id);


--
-- Name: code_symbols_unique_id_6564592d_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX code_symbols_unique_id_6564592d_like ON public.code_symbols USING btree (unique_id varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: embedding_batch_jobs_batch_id_c4c78fc5_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX embedding_batch_jobs_batch_id_c4c78fc5_like ON public.embedding_batch_jobs USING btree (batch_id varchar_pattern_ops);


--
-- Name: embedding_batch_jobs_repository_id_ab9f817f; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX embedding_batch_jobs_repository_id_ab9f817f ON public.embedding_batch_jobs USING btree (repository_id);


--
-- Name: embedding_batch_jobs_status_a3a1d0be; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX embedding_batch_jobs_status_a3a1d0be ON public.embedding_batch_jobs USING btree (status);


--
-- Name: embedding_batch_jobs_status_a3a1d0be_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX embedding_batch_jobs_status_a3a1d0be_like ON public.embedding_batch_jobs USING btree (status varchar_pattern_ops);


--
-- Name: knowledge_chunks_chunk_type_6e7580c3; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX knowledge_chunks_chunk_type_6e7580c3 ON public.knowledge_chunks USING btree (chunk_type);


--
-- Name: knowledge_chunks_chunk_type_6e7580c3_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX knowledge_chunks_chunk_type_6e7580c3_like ON public.knowledge_chunks USING btree (chunk_type varchar_pattern_ops);


--
-- Name: knowledge_chunks_related_class_id_892bc260; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX knowledge_chunks_related_class_id_892bc260 ON public.knowledge_chunks USING btree (related_class_id);


--
-- Name: knowledge_chunks_related_file_id_95acf5f6; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX knowledge_chunks_related_file_id_95acf5f6 ON public.knowledge_chunks USING btree (related_file_id);


--
-- Name: knowledge_chunks_related_symbol_id_d6fbc86d; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX knowledge_chunks_related_symbol_id_d6fbc86d ON public.knowledge_chunks USING btree (related_symbol_id);


--
-- Name: knowledge_chunks_repository_id_f4ef7cf6; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX knowledge_chunks_repository_id_f4ef7cf6 ON public.knowledge_chunks USING btree (repository_id);


--
-- Name: knowledge_embedding_hnsw_l2_idx; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX knowledge_embedding_hnsw_l2_idx ON public.knowledge_chunks USING hnsw (embedding public.vector_l2_ops) WITH (m='16', ef_construction='64');


--
-- Name: repositories_full_name_548baf46_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX repositories_full_name_548baf46_like ON public.repositories USING btree (full_name varchar_pattern_ops);


--
-- Name: repositories_user_id_89419cc6; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX repositories_user_id_89419cc6 ON public.repositories USING btree (user_id);


--
-- Name: repository__reposit_7bf3c6_idx; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX repository__reposit_7bf3c6_idx ON public.repository_insights USING btree (repository_id, commit_hash);


--
-- Name: repository_insights_commit_hash_9f5e3bdd; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX repository_insights_commit_hash_9f5e3bdd ON public.repository_insights USING btree (commit_hash);


--
-- Name: repository_insights_commit_hash_9f5e3bdd_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX repository_insights_commit_hash_9f5e3bdd_like ON public.repository_insights USING btree (commit_hash varchar_pattern_ops);


--
-- Name: repository_insights_insight_type_1016d168; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX repository_insights_insight_type_1016d168 ON public.repository_insights USING btree (insight_type);


--
-- Name: repository_insights_insight_type_1016d168_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX repository_insights_insight_type_1016d168_like ON public.repository_insights USING btree (insight_type varchar_pattern_ops);


--
-- Name: repository_insights_is_resolved_b35fedaa; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX repository_insights_is_resolved_b35fedaa ON public.repository_insights USING btree (is_resolved);


--
-- Name: repository_insights_related_symbol_id_f3419e55; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX repository_insights_related_symbol_id_f3419e55 ON public.repository_insights USING btree (related_symbol_id);


--
-- Name: repository_insights_repository_id_ff232e03; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX repository_insights_repository_id_ff232e03 ON public.repository_insights USING btree (repository_id);


--
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);


--
-- Name: socialaccount_socialapp_sites_site_id_2579dee5; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX socialaccount_socialapp_sites_site_id_2579dee5 ON public.socialaccount_socialapp_sites USING btree (site_id);


--
-- Name: socialaccount_socialapp_sites_socialapp_id_97fb6e7d; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX socialaccount_socialapp_sites_socialapp_id_97fb6e7d ON public.socialaccount_socialapp_sites USING btree (socialapp_id);


--
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);


--
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);


--
-- Name: unique_primary_email; Type: INDEX; Schema: public; Owner: helix
--

CREATE UNIQUE INDEX unique_primary_email ON public.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- Name: unique_verified_email; Type: INDEX; Schema: public; Owner: helix
--

CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


--
-- Name: user_notifications_repository_id_a99c98d8; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX user_notifications_repository_id_a99c98d8 ON public.user_notifications USING btree (repository_id);


--
-- Name: user_notifications_user_id_0ac00350; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX user_notifications_user_id_0ac00350 ON public.user_notifications USING btree (user_id);


--
-- Name: users_groups_customuser_id_4bd991a9; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX users_groups_customuser_id_4bd991a9 ON public.users_groups USING btree (customuser_id);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_user_permissions_customuser_id_efdb305c; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX users_user_permissions_customuser_id_efdb305c ON public.users_user_permissions USING btree (customuser_id);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_username_e8658fc8_like; Type: INDEX; Schema: public; Owner: helix
--

CREATE INDEX users_username_e8658fc8_like ON public.users USING btree (username varchar_pattern_ops);


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: async_task_statuses async_task_statuses_repository_id_f116b5f6_fk_repositories_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.async_task_statuses
    ADD CONSTRAINT async_task_statuses_repository_id_f116b5f6_fk_repositories_id FOREIGN KEY (repository_id) REFERENCES public.repositories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: async_task_statuses async_task_statuses_user_id_aad9e929_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.async_task_statuses
    ADD CONSTRAINT async_task_statuses_user_id_aad9e929_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: code_classes code_classes_code_file_id_e9e939cc_fk_code_files_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_classes
    ADD CONSTRAINT code_classes_code_file_id_e9e939cc_fk_code_files_id FOREIGN KEY (code_file_id) REFERENCES public.code_files(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: code_dependencies code_dependencies_callee_id_b1ace185_fk_code_symbols_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_dependencies
    ADD CONSTRAINT code_dependencies_callee_id_b1ace185_fk_code_symbols_id FOREIGN KEY (callee_id) REFERENCES public.code_symbols(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: code_dependencies code_dependencies_caller_id_34f358d9_fk_code_symbols_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_dependencies
    ADD CONSTRAINT code_dependencies_caller_id_34f358d9_fk_code_symbols_id FOREIGN KEY (caller_id) REFERENCES public.code_symbols(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: code_files code_files_repository_id_d41da00e_fk_repositories_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_files
    ADD CONSTRAINT code_files_repository_id_d41da00e_fk_repositories_id FOREIGN KEY (repository_id) REFERENCES public.repositories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: code_symbols code_symbols_code_class_id_fd669541_fk_code_classes_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_symbols
    ADD CONSTRAINT code_symbols_code_class_id_fd669541_fk_code_classes_id FOREIGN KEY (code_class_id) REFERENCES public.code_classes(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: code_symbols code_symbols_code_file_id_b3ae3485_fk_code_files_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.code_symbols
    ADD CONSTRAINT code_symbols_code_file_id_b3ae3485_fk_code_files_id FOREIGN KEY (code_file_id) REFERENCES public.code_files(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: embedding_batch_jobs embedding_batch_jobs_repository_id_ab9f817f_fk_repositories_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.embedding_batch_jobs
    ADD CONSTRAINT embedding_batch_jobs_repository_id_ab9f817f_fk_repositories_id FOREIGN KEY (repository_id) REFERENCES public.repositories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: knowledge_chunks knowledge_chunks_related_class_id_892bc260_fk_code_classes_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT knowledge_chunks_related_class_id_892bc260_fk_code_classes_id FOREIGN KEY (related_class_id) REFERENCES public.code_classes(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: knowledge_chunks knowledge_chunks_related_file_id_95acf5f6_fk_code_files_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT knowledge_chunks_related_file_id_95acf5f6_fk_code_files_id FOREIGN KEY (related_file_id) REFERENCES public.code_files(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: knowledge_chunks knowledge_chunks_related_symbol_id_d6fbc86d_fk_code_symbols_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT knowledge_chunks_related_symbol_id_d6fbc86d_fk_code_symbols_id FOREIGN KEY (related_symbol_id) REFERENCES public.code_symbols(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: knowledge_chunks knowledge_chunks_repository_id_f4ef7cf6_fk_repositories_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT knowledge_chunks_repository_id_f4ef7cf6_fk_repositories_id FOREIGN KEY (repository_id) REFERENCES public.repositories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: repositories repositories_user_id_89419cc6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.repositories
    ADD CONSTRAINT repositories_user_id_89419cc6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: repository_insights repository_insights_related_symbol_id_f3419e55_fk_code_symb; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.repository_insights
    ADD CONSTRAINT repository_insights_related_symbol_id_f3419e55_fk_code_symb FOREIGN KEY (related_symbol_id) REFERENCES public.code_symbols(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: repository_insights repository_insights_repository_id_ff232e03_fk_repositories_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.repository_insights
    ADD CONSTRAINT repository_insights_repository_id_ff232e03_fk_repositories_id FOREIGN KEY (repository_id) REFERENCES public.repositories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_site_id_2579dee5_fk_django_si; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc FOREIGN KEY (socialapp_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_user_id_8146e70c_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_notifications user_notifications_repository_id_a99c98d8_fk_repositories_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT user_notifications_repository_id_a99c98d8_fk_repositories_id FOREIGN KEY (repository_id) REFERENCES public.repositories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_notifications user_notifications_user_id_0ac00350_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT user_notifications_user_id_0ac00350_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_customuser_id_4bd991a9_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_customuser_id_4bd991a9_fk_users_id FOREIGN KEY (customuser_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_customuser_id_efdb305c_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: helix
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_customuser_id_efdb305c_fk_users_id FOREIGN KEY (customuser_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: async_task_statuses; Type: ROW SECURITY; Schema: public; Owner: helix
--

ALTER TABLE public.async_task_statuses ENABLE ROW LEVEL SECURITY;

--
-- Name: code_classes; Type: ROW SECURITY; Schema: public; Owner: helix
--

ALTER TABLE public.code_classes ENABLE ROW LEVEL SECURITY;

--
-- Name: code_dependencies; Type: ROW SECURITY; Schema: public; Owner: helix
--

ALTER TABLE public.code_dependencies ENABLE ROW LEVEL SECURITY;

--
-- Name: code_files; Type: ROW SECURITY; Schema: public; Owner: helix
--

ALTER TABLE public.code_files ENABLE ROW LEVEL SECURITY;

--
-- Name: code_symbols; Type: ROW SECURITY; Schema: public; Owner: helix
--

ALTER TABLE public.code_symbols ENABLE ROW LEVEL SECURITY;

--
-- Name: embedding_batch_jobs; Type: ROW SECURITY; Schema: public; Owner: helix
--

ALTER TABLE public.embedding_batch_jobs ENABLE ROW LEVEL SECURITY;

--
-- Name: knowledge_chunks; Type: ROW SECURITY; Schema: public; Owner: helix
--

ALTER TABLE public.knowledge_chunks ENABLE ROW LEVEL SECURITY;

--
-- Name: repositories; Type: ROW SECURITY; Schema: public; Owner: helix
--

ALTER TABLE public.repositories ENABLE ROW LEVEL SECURITY;

--
-- Name: repository_insights; Type: ROW SECURITY; Schema: public; Owner: helix
--

ALTER TABLE public.repository_insights ENABLE ROW LEVEL SECURITY;

--
-- Name: async_task_statuses user_isolation_policy; Type: POLICY; Schema: public; Owner: helix
--

CREATE POLICY user_isolation_policy ON public.async_task_statuses FOR SELECT USING ((user_id = (current_setting('app.current_user_id'::text, true))::integer));


--
-- Name: code_classes user_isolation_policy; Type: POLICY; Schema: public; Owner: helix
--

CREATE POLICY user_isolation_policy ON public.code_classes FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.code_files
  WHERE (code_files.id = code_classes.code_file_id))));


--
-- Name: code_dependencies user_isolation_policy; Type: POLICY; Schema: public; Owner: helix
--

CREATE POLICY user_isolation_policy ON public.code_dependencies FOR SELECT USING (((EXISTS ( SELECT 1
   FROM public.code_symbols
  WHERE (code_symbols.id = code_dependencies.caller_id))) AND (EXISTS ( SELECT 1
   FROM public.code_symbols
  WHERE (code_symbols.id = code_dependencies.callee_id)))));


--
-- Name: code_files user_isolation_policy; Type: POLICY; Schema: public; Owner: helix
--

CREATE POLICY user_isolation_policy ON public.code_files FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.repositories
  WHERE (repositories.id = code_files.repository_id))));


--
-- Name: code_symbols user_isolation_policy; Type: POLICY; Schema: public; Owner: helix
--

CREATE POLICY user_isolation_policy ON public.code_symbols FOR SELECT USING ((((code_file_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM public.code_files
  WHERE (code_files.id = code_symbols.code_file_id)))) OR ((code_class_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM public.code_classes
  WHERE (code_classes.id = code_symbols.code_class_id))))));


--
-- Name: embedding_batch_jobs user_isolation_policy; Type: POLICY; Schema: public; Owner: helix
--

CREATE POLICY user_isolation_policy ON public.embedding_batch_jobs FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.repositories
  WHERE (repositories.id = embedding_batch_jobs.repository_id))));


--
-- Name: knowledge_chunks user_isolation_policy; Type: POLICY; Schema: public; Owner: helix
--

CREATE POLICY user_isolation_policy ON public.knowledge_chunks FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.repositories
  WHERE (repositories.id = knowledge_chunks.repository_id))));


--
-- Name: repositories user_isolation_policy; Type: POLICY; Schema: public; Owner: helix
--

CREATE POLICY user_isolation_policy ON public.repositories FOR SELECT USING ((user_id = (current_setting('app.current_user_id'::text, true))::integer));


--
-- Name: repository_insights user_isolation_policy; Type: POLICY; Schema: public; Owner: helix
--

CREATE POLICY user_isolation_policy ON public.repository_insights FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.repositories
  WHERE (repositories.id = repository_insights.repository_id))));


--
-- Name: user_notifications user_isolation_policy; Type: POLICY; Schema: public; Owner: helix
--

CREATE POLICY user_isolation_policy ON public.user_notifications FOR SELECT USING ((user_id = (current_setting('app.current_user_id'::text, true))::integer));


--
-- Name: user_notifications; Type: ROW SECURITY; Schema: public; Owner: helix
--

ALTER TABLE public.user_notifications ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO helix_readonly;


--
-- Name: TABLE async_task_statuses; Type: ACL; Schema: public; Owner: helix
--

GRANT SELECT ON TABLE public.async_task_statuses TO helix_readonly;


--
-- Name: TABLE code_classes; Type: ACL; Schema: public; Owner: helix
--

GRANT SELECT ON TABLE public.code_classes TO helix_readonly;


--
-- Name: TABLE code_dependencies; Type: ACL; Schema: public; Owner: helix
--

GRANT SELECT ON TABLE public.code_dependencies TO helix_readonly;


--
-- Name: TABLE code_files; Type: ACL; Schema: public; Owner: helix
--

GRANT SELECT ON TABLE public.code_files TO helix_readonly;


--
-- Name: TABLE code_symbols; Type: ACL; Schema: public; Owner: helix
--

GRANT SELECT ON TABLE public.code_symbols TO helix_readonly;


--
-- Name: TABLE embedding_batch_jobs; Type: ACL; Schema: public; Owner: helix
--

GRANT SELECT ON TABLE public.embedding_batch_jobs TO helix_readonly;


--
-- Name: TABLE knowledge_chunks; Type: ACL; Schema: public; Owner: helix
--

GRANT SELECT ON TABLE public.knowledge_chunks TO helix_readonly;


--
-- Name: TABLE repositories; Type: ACL; Schema: public; Owner: helix
--

GRANT SELECT ON TABLE public.repositories TO helix_readonly;


--
-- Name: TABLE repository_insights; Type: ACL; Schema: public; Owner: helix
--

GRANT SELECT ON TABLE public.repository_insights TO helix_readonly;


--
-- Name: TABLE user_notifications; Type: ACL; Schema: public; Owner: helix
--

GRANT SELECT ON TABLE public.user_notifications TO helix_readonly;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: helix
--

ALTER DEFAULT PRIVILEGES FOR ROLE helix IN SCHEMA public GRANT SELECT ON TABLES  TO helix_readonly;


--
-- PostgreSQL database dump complete
--

